version: '3'

services:
  category-app:
    container_name: php
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - category-app-mysql
      - category-app-redis

  category-app-mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: category_app
      MYSQL_ROOT_PASSWORD: root

  category-app-nginx:
    container_name: nginx
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - category-app

  category-app-redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379