<?php

namespace Database\Seeders\Lookup;

use Illuminate\Database\Seeder;
use DB;

class PMS0045Seeder extends Seeder
{
    public function run()
    {
        DB::connection('oracle_toat')->table('pt_program_columns_info')->insert($this->programColumns());
                  
    }

    public function programColumns()
    {
        $programCode = 'PMS0045';

        $lists = [];

            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'LOOKUP_CODE',
                'COLUMN_PROMPT'        => 'LOOKUP_CODE',
                'ENABLE_FLAG'          => 'Y',
                'COLUMN_SEQ_NUM'       => 1,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);

            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'MEANING',
                'COLUMN_PROMPT'        => 'MEANING',
                'ENABLE_FLAG'          => 'Y',
                'COLUMN_SEQ_NUM'       => 2,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);

            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'DESCRIPTION',
                'COLUMN_PROMPT'        => 'DESCRIPTION',
                'ENABLE_FLAG'          => 'Y',
                'COLUMN_SEQ_NUM'       => 3,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);

            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'START_DATE_ACTIVE',
                'COLUMN_PROMPT'        => 'START_DATE_ACTIVE',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 4,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'END_DATE_ACTIVE',
                'COLUMN_PROMPT'        => 'END_DATE_ACTIVE',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 5,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'TAG',
                'COLUMN_PROMPT'        => 'TAG',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 6,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ENABLED_FLAG',
                'COLUMN_PROMPT'        => 'ENABLED_FLAG',
                'ENABLE_FLAG'          => 'Y',
                'COLUMN_SEQ_NUM'       => 7,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE1',
                'COLUMN_PROMPT'        => 'ATTRIBUTE1',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 8,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE2',
                'COLUMN_PROMPT'        => 'ATTRIBUTE2',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 9,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE3',
                'COLUMN_PROMPT'        => 'ATTRIBUTE3',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 10,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE4',
                'COLUMN_PROMPT'        => 'ATTRIBUTE4',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 11,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE5',
                'COLUMN_PROMPT'        => 'ATTRIBUTE5',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 12,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE6',
                'COLUMN_PROMPT'        => 'ATTRIBUTE6',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 13,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE7',
                'COLUMN_PROMPT'        => 'ATTRIBUTE7',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 14,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE8',
                'COLUMN_PROMPT'        => 'ATTRIBUTE8',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 15,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE9',
                'COLUMN_PROMPT'        => 'ATTRIBUTE9',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 16,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE10',
                'COLUMN_PROMPT'        => 'ATTRIBUTE10',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 17,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE11',
                'COLUMN_PROMPT'        => 'ATTRIBUTE11',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 18,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE12',
                'COLUMN_PROMPT'        => 'ATTRIBUTE12',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 19,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE13',
                'COLUMN_PROMPT'        => 'ATTRIBUTE13',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 20,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE14',
                'COLUMN_PROMPT'        => 'ATTRIBUTE14',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 21,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]);
            
            array_push($lists, [
                'PROGRAM_CODE'         => $programCode,
                'COLUMN_NAME'          => 'ATTRIBUTE15',
                'COLUMN_PROMPT'        => 'ATTRIBUTE15',
                'ENABLE_FLAG'          => 'N',
                'COLUMN_SEQ_NUM'       => 22,
                'VIEW_NAME'            => NULL,
                'FLEX_NAME'            => NULL,
                'SQL_TEXT'             => NULL,
                'DESCRIPTION'          => NULL,
                'ATTRIBUTE_CATEGORY'   => NULL,
                'ATTRIBUTE1'           => NULL,
                'ATTRIBUTE2'           => NULL,
                'ATTRIBUTE3'           => NULL,
                'ATTRIBUTE4'           => NULL,
                'ATTRIBUTE5'           => NULL,
                'ATTRIBUTE6'           => NULL,
                'ATTRIBUTE7'           => NULL,
                'ATTRIBUTE8'           => NULL,
                'ATTRIBUTE9'           => NULL,
                'ATTRIBUTE10'          => NULL,
                'ATTRIBUTE11'          => NULL,
                'ATTRIBUTE12'          => NULL,
                'ATTRIBUTE13'          => NULL,
                'ATTRIBUTE14'          => NULL,
                'ATTRIBUTE15'          => NULL,
                'CREATED_BY'           => NULL,
                'CREATION_DATE'        => NULL,
                'LAST_UPDATED_BY'      => NULL,
                'LAST_UPDATE_DATE'     => NULL,
                'REQUIRED_FLAG'        => NULL,
                'SQL_TEXT_DISPLAY'     => NULL,
                'INPUT_TYPE'           => NULL, 
            ]); 
        
        return $lists;
    }
}
