<?php

namespace App\Models\PM;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use DB;

class MtlLotNumber extends Model
{
    use HasFactory;

    protected $table = 'MTL_LOT_NUMBERS';
    public $timestamps = false;

    protected $fillable = [
    ];

    public static function getListLotNumbers($organizationId) {

        return DB::table('MTL_LOT_NUMBERS')
            ->select(DB::raw('ORG_ORGANIZATION_DEFINITIONS.ORGANIZATION_ID, ORG_ORGANIZATION_DEFINITIONS.ORGANIZATION_CODE, MTL_LOT_NUMBERS.ORIGINATION_DATE AS TRANSACTION_DATE, MTL_LOT_NUMBERS.LOT_NUMBER, MTL_LOT_NUMBERS.INVENTORY_ITEM_ID, MTL_SYSTEM_ITEMS_B.SEGMENT1 AS ITEM_NUMBER, MTL_SYSTEM_ITEMS_B.DESCRIPTION AS ITEM_DESC, MTL_ONHAND_QUANTITIES.SUBINVENTORY_CODE, MTL_ONHAND_QUANTITIES.LOCATOR_ID, SUM(MTL_ONHAND_QUANTITIES.TRANSACTION_QUANTITY) AS TRANSACTION_QUANTITY, MTL_SYSTEM_ITEMS_B.PRIMARY_UOM_CODE AS TRANSACTION_UOM'))
            ->join('MTL_SYSTEM_ITEMS_B', 'MTL_LOT_NUMBERS.INVENTORY_ITEM_ID', '=', 'MTL_SYSTEM_ITEMS_B.INVENTORY_ITEM_ID')
            ->join('ORG_ORGANIZATION_DEFINITIONS', 'MTL_LOT_NUMBERS.ORGANIZATION_ID', '=', 'ORG_ORGANIZATION_DEFINITIONS.ORGANIZATION_ID')
            ->join('MTL_ONHAND_QUANTITIES', 'MTL_LOT_NUMBERS.INVENTORY_ITEM_ID', '=', 'MTL_ONHAND_QUANTITIES.INVENTORY_ITEM_ID')
            ->whereRaw('MTL_LOT_NUMBERS.ORGANIZATION_ID = MTL_ONHAND_QUANTITIES.ORGANIZATION_ID')
            ->whereRaw('MTL_LOT_NUMBERS.ORGANIZATION_ID = MTL_SYSTEM_ITEMS_B.ORGANIZATION_ID')
            ->whereRaw('MTL_LOT_NUMBERS.LOT_NUMBER = MTL_ONHAND_QUANTITIES.LOT_NUMBER')
            ->where('MTL_LOT_NUMBERS.ORGANIZATION_ID', $organizationId)
            ->groupBy('ORG_ORGANIZATION_DEFINITIONS.ORGANIZATION_ID', 
                'ORG_ORGANIZATION_DEFINITIONS.ORGANIZATION_CODE', 
                'MTL_LOT_NUMBERS.ORIGINATION_DATE', 
                'MTL_LOT_NUMBERS.LOT_NUMBER', 
                'MTL_LOT_NUMBERS.INVENTORY_ITEM_ID', 
                'MTL_SYSTEM_ITEMS_B.SEGMENT1', 
                'MTL_SYSTEM_ITEMS_B.DESCRIPTION', 
                'MTL_SYSTEM_ITEMS_B.PRIMARY_UOM_CODE',
                'MTL_ONHAND_QUANTITIES.SUBINVENTORY_CODE', 
                'MTL_ONHAND_QUANTITIES.LOCATOR_ID'
            )
            ->orderBy('MTL_LOT_NUMBERS.LOT_NUMBER');

    }

}