<?php

namespace Database\Seeders\CT;

use Illuminate\Database\Seeder;
use App\Models\CT\CostCenterProductionProcess;
use DB;

class ProductionProcessTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CostCenterProductionProcess::insert([
            [
                'cost_center_id' => 1,
                'production_process_code' => "10",
                'production_process_name' => "ยาหมัก",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 1,
                'production_process_code' => '20',
                'production_process_name' => "ยาเส้นปรุง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 2,
                'production_process_code' => '01',
                'production_process_name' => "ให้ความชื้นและหมัก",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 2,
                'production_process_code' => '02',
                'production_process_name' => "หั่นยาเส้น",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 2,
                'production_process_code' => '03',
                'production_process_name' => "ยาเส้นพอง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 3,
                'production_process_code' => '03',
                'production_process_name' => "มวน",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 3,
                'production_process_code' => '04',
                'production_process_name' => "บรรจุซอง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 3,
                'production_process_code' => '05',
                'production_process_name' => "บรรจุห่อ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 3,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุหีบ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 4,
                'production_process_code' => '03',
                'production_process_name' => "มวน",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 4,
                'production_process_code' => '04',
                'production_process_name' => "บรรจุซอง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 4,
                'production_process_code' => '05',
                'production_process_name' => "บรรจุห่อ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 4,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุหีบ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 5,
                'production_process_code' => '01',
                'production_process_name' => "มวนก้นกรอง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 6,
                'production_process_code' => '01',
                'production_process_name' => "Foil Solution",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 7,
                'production_process_code' => '03',
                'production_process_name' => "พิมพ์",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 7,
                'production_process_code' => '04',
                'production_process_name' => "ตัด",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 7,
                'production_process_code' => '05',
                'production_process_name' => "คัดเลือก",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 7,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '01',
                'production_process_name' => "พิมพ์ สี 1-2",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '02',
                'production_process_name' => "พิมพ์ สี 3-4",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '03',
                'production_process_name' => "พิมพ์",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '04',
                'production_process_name' => "ตัด",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '05',
                'production_process_name' => "คัดเลือก",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 8,
                'production_process_code' => '07',
                'production_process_name' => "ส่งคลัง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 9,
                'production_process_code' => '01',
                'production_process_name' => "ให้ความชื้นและหมัก",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 9,
                'production_process_code' => '02',
                'production_process_name' => "หั่นยาเส้น",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 9,
                'production_process_code' => '03',
                'production_process_name' => "ยาเส้นพอง",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 9,
                'production_process_code' => '05',
                'production_process_name' => "บรรจุซอง/ห่อ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 9,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุหีบ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 10,
                'production_process_code' => '01',
                'production_process_name' => "การอบใบยา",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 11,
                'production_process_code' => '01',
                'production_process_name' => "วัตถุดิบอบใบยา",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 12,
                'production_process_code' => '01',
                'production_process_name' => "ใบยาหั่น",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],

            [
                'cost_center_id' => 13,
                'production_process_code' => '01',
                'production_process_name' => "ผสมใบยา",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 13,
                'production_process_code' => '02',
                'production_process_name' => "หั่นและคั่ว",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 14,
                'production_process_code' => '05',
                'production_process_name' => "บรรจุซอง/ห่อ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 14,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุหีบ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],

            [
                'cost_center_id' => 15,
                'production_process_code' => '01',
                'production_process_name' => "จ้างทำความสะอาด",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 16,
                'production_process_code' => null,
                'production_process_name' => null,
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 17,
                'production_process_code' => null,
                'production_process_name' => null,
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 18,
                'production_process_code' => '01',
                'production_process_name' => "พิมพ์ สี 1-2",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 18,
                'production_process_code' => '02',
                'production_process_name' => "พิมพ์ สี 3-4",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 18,
                'production_process_code' => '03',
                'production_process_name' => "พิมพ์",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 18,
                'production_process_code' => '04',
                'production_process_name' => "ตัด",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 18,
                'production_process_code' => '05',
                'production_process_name' => "คัดเลือก",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
            [
                'cost_center_id' => 18,
                'production_process_code' => '06',
                'production_process_name' => "บรรจุ",
                'percen_of_wage' => 0,
                'percen_of_cp_vc' => 0,
                'percen_of_cp_fe' => 0,
            ],
        ]);
    }
}
